runtime: php82
handlers:
- url: /
  script: index.php
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
# Serve php scripts.
- url: /(.+\.php)$
  script: \1
env_variables:
  MYSQL_HOST: "34.31.243.0"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: ""